test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -101,7 +101,9 @@ jobs:
       - name: Create Database and Tables from SQL File
         run: |
           export PGPASSWORD=sa
-          psql -h localhost -U postgres -d blog_platform -f setup.sql
+          psql -h localhost -U postgres -c 'CREATE DATABASE blog_platform;' || { echo 'Failed to create database'; exit 1; }
+          sleep 5
+          psql -h localhost -U postgres -d blog_platform -f setup.sql || { echo 'Failed to set up database'; exit 1; }
 
       - name: Run e2e tests
         run: yarn test:e2e
